# Variable 'ContainerRepository' was defined in the Variables tab
variables:
- name: BuildParameters.RestoreBuildProjects
  value: '**/*.csproj'
- name: BuildParameters.TestProjects
  value: '**/*[Tt]ests/*.csproj'
name: $(date:yyyyMMdd)$(rev:.r)
resources:
  repositories:
  - repository: self
    type: git
    ref: refs/heads/main
jobs:
- job: Job_1
  displayName: Agent job 1
  pool:
    vmImage: ubuntu-latest
  steps:
  - checkout: self
    clean: true
  - task: DotNetCoreCLI@2
    displayName: Restore
    inputs:
      command: restore
      projects: $(BuildParameters.RestoreBuildProjects)
  - task: DotNetCoreCLI@2
    displayName: Build
    inputs:
      projects: $(BuildParameters.RestoreBuildProjects)
      arguments: --configuration $(BuildConfiguration)
  - task: DotNetCoreCLI@2
    displayName: Test
    inputs:
      command: test
      projects: $(BuildParameters.TestProjects)
      arguments: --configuration $(BuildConfiguration)
  - task: DotNetCoreCLI@2
    displayName: Publish
    inputs:
      command: publish
      publishWebProjects: True
      projects: $(BuildParameters.RestoreBuildProjects)
      arguments: --configuration $(BuildConfiguration) --runtime linux-x64 --self-contained false --output $(build.artifactstagingdirectory)/output
      zipAfterPublish: false
      modifyOutputPath: false
  - task: Docker@2
    displayName: build
    inputs:
      containerRegistry: 8c8a9000-30e2-42cf-9ec6-e4fa0601a7ec
      repository: $(ContainerRepository)
      command: build
      buildContext: $(Build.ArtifactStagingDirectory)
      tags: $(Build.BuildNumber)
      arguments: --build-arg output=./output
  - task: Docker@2
    displayName: push
    inputs:
      containerRegistry: 8c8a9000-30e2-42cf-9ec6-e4fa0601a7ec
      repository: $(ContainerRepository)
      command: push
      tags: $(Build.BuildNumber)
  - task: PublishBuildArtifacts@1
    displayName: Publish Artifact
    condition: succeededOrFailed()
    inputs:
      PathtoPublish: $(build.artifactstagingdirectory)/output
      TargetPath: '\\my\share\$(Build.DefinitionName)\$(Build.BuildNumber)'
...
